# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_returnrecord_reset_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='remain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='数目'),
        ),
        migrations.AlterField(
            model_name='goodsaddrecord',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='数目'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='sell_num',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='数目'),
        ),
        migrations.AlterField(
            model_name='returnrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='数目'),
        ),
        migrations.AlterField(
            model_name='transfergoods',
            name='change_num',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='数目'),
        ),
    ]
