# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_recordhistory_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordhistory',
            options={'ordering': ['-date'], 'verbose_name': '历史订单查看', 'verbose_name_plural': '历史订单查看'},
        ),
        migrations.AddField(
            model_name='recordhistory',
            name='arrears',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_arrears', to='store.ArrearsPrice'),
        ),
    ]
