# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 02:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrearsPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrears_price', models.FloatField(verbose_name='欠款额')),
                ('is_arrears', models.BooleanField(default=False, verbose_name='清除欠款')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name_plural': '欠款记录',
                'verbose_name': '欠款记录',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('name', models.CharField(max_length=20, verbose_name='类别名称')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('super_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='所属分类')),
            ],
            options={
                'ordering': ['add_date'],
                'verbose_name_plural': '类别',
                'verbose_name': '类别',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系地址')),
                ('phone_number', models.CharField(max_length=20, verbose_name='联系电话')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('user_name', models.CharField(max_length=15, verbose_name='客户姓名')),
            ],
            options={
                'verbose_name_plural': '客户',
                'verbose_name': '客户',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=15, unique=True, verbose_name='商品名称')),
                ('average_price', models.FloatField(default=0, verbose_name='进价')),
                ('last_price', models.FloatField(default=0, verbose_name='售价')),
                ('unit_name', models.CharField(max_length=10, verbose_name='单位')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='更新日期')),
                ('recent_sell', models.DateField(blank=True, null=True, verbose_name='最近售出日期')),
                ('is_delete', models.BooleanField(default=False, verbose_name='下架')),
                ('remain', models.IntegerField(default=0, verbose_name='库存量')),
                ('last_time', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('add_people', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('category', models.ManyToManyField(to='store.Category', verbose_name='所属类别')),
            ],
            options={
                'ordering': ['last_time', 'goods_name', 'update_date'],
                'verbose_name_plural': '商品',
                'verbose_name': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsAddRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='数目')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='说明信息')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('new_price', models.FloatField(blank=True, null=True, verbose_name='新进价')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Goods', verbose_name='商品名称')),
            ],
            options={
                'ordering': ['goods', 'number'],
                'verbose_name_plural': '增加库存记录',
                'verbose_name': '增加库存记录',
            },
        ),
        migrations.CreateModel(
            name='GoodsSellRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_num', models.IntegerField(verbose_name='销售数目')),
                ('average_price', models.FloatField(blank=True, null=True, verbose_name='进价')),
                ('sell_price', models.FloatField(blank=True, null=True, verbose_name='售价')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('arrears', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrears', to='store.ArrearsPrice', verbose_name='欠款额')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='store.Customer', verbose_name='客户姓名')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='store.Goods', verbose_name='商品名称')),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
            ],
            options={
                'ordering': ['-date', 'goods', 'sell_num'],
                'verbose_name_plural': '销售记录',
                'verbose_name': '销售记录',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_price', models.FloatField(default=0, verbose_name='总价')),
                ('all_profit', models.FloatField(default=0, verbose_name='总利润')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否取消订单')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer', verbose_name='客户名称')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name_plural': '订单记录',
                'verbose_name': '订单记录',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='志平电子配件销售清单', max_length=100, verbose_name='标题')),
                ('alias', models.CharField(default='默认模板', max_length=20, verbose_name='模板名字')),
                ('ad', models.TextField(verbose_name='广告语')),
                ('phone', models.CharField(default='7566409 13755519477', max_length=50, verbose_name='电话号码')),
                ('address', models.CharField(default='芦溪县凌云南路太阳城B栋良友旁', max_length=50, verbose_name='地址')),
                ('remark', models.TextField(blank=True, default='银行卡号: 6222.0215 0400 3618 261\n中国银行: 6216 6165 0600 0292 464', null=True, verbose_name='附加信息')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('tag', models.BooleanField(default=True, verbose_name='默认模板')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name_plural': '设置清单',
                'verbose_name': '设置清单',
            },
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('type', models.IntegerField(choices=[(0, '操作失误'), (1, '退货')], verbose_name='退送原因')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='说明信息')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Goods', verbose_name='商品名称')),
            ],
            options={
                'ordering': ['goods', 'amount'],
                'verbose_name_plural': '退送库存记录',
                'verbose_name': '退送库存记录',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系地址')),
                ('phone_number', models.CharField(max_length=20, verbose_name='联系电话')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('user_name', models.CharField(max_length=15, verbose_name='供货商姓名')),
                ('shop_name', models.CharField(max_length=20, unique=True, verbose_name='供货商名称')),
                ('shop_address', models.CharField(max_length=100, verbose_name='供货商地址')),
            ],
            options={
                'ordering': ['shop_name'],
                'verbose_name_plural': '供货商',
                'verbose_name': '供货商',
            },
        ),
        migrations.CreateModel(
            name='TransferGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_num', models.IntegerField(verbose_name='交易数量')),
                ('from_price', models.FloatField(default=0, verbose_name='进价')),
                ('to_price', models.FloatField(default=0, verbose_name='售价')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='说明信息')),
                ('from_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_shop', to='store.Shop', verbose_name='供应商')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Goods', verbose_name='商品名称')),
                ('to_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_name', to='store.Shop', verbose_name='销售商')),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
            ],
            options={
                'ordering': ['goods', 'change_num'],
                'verbose_name_plural': '直接交易记录',
                'verbose_name': '直接交易记录',
            },
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shop', verbose_name='供货商名称'),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='order',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Report', verbose_name='清单模板'),
        ),
        migrations.AddField(
            model_name='order',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人员'),
        ),
        migrations.AddField(
            model_name='goodsaddrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shop', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='goodsaddrecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='goods',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Shop', verbose_name='供应商名称'),
        ),
        migrations.AddField(
            model_name='arrearsprice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer', verbose_name='客户姓名'),
        ),
    ]
