# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrearsprice',
            name='arrears_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='欠款额'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='进价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='goodsaddrecord',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='新进价'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='进价'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='all_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='all_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总利润'),
        ),
        migrations.AlterField(
            model_name='transfergoods',
            name='from_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='进价'),
        ),
        migrations.AlterField(
            model_name='transfergoods',
            name='to_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='售价'),
        ),
    ]
