# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20161216_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='add_people',
            new_name='updater',
        ),
    ]
