# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20161012_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodssellrecord',
            options={'ordering': ['goods', 'sell_num'], 'verbose_name': '销售记录', 'verbose_name_plural': '销售记录'},
        ),
        migrations.RemoveField(
            model_name='goodssellrecord',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='average_price',
            field=models.FloatField(verbose_name='进价'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='store.Customer', verbose_name='客户姓名'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='store.Goods', verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='is_arrears',
            field=models.BooleanField(verbose_name='是否欠款'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='描述信息'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='sell_num',
            field=models.IntegerField(verbose_name='销售数目'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='sell_price',
            field=models.FloatField(verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='store.Shop', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='操作人员'),
        ),
    ]
