# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170118_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_customer', to='store.Customer', verbose_name='客户姓名')),
            ],
        ),
        migrations.AlterModelManagers(
            name='goodssellrecord',
            managers=[
                ('statistic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_customer', to='store.Customer', verbose_name='退货用户'),
        ),
        migrations.AddField(
            model_name='goodssellrecord',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_many_record', to='store.RecordHistory'),
        ),
    ]
