# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_super_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsshop',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='goodsshop',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goodsshop',
            name='last_updater',
        ),
        migrations.RemoveField(
            model_name='goodsshop',
            name='remain',
        ),
        migrations.RemoveField(
            model_name='goodsshop',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='goodsshop',
            name='update_date',
        ),
        migrations.AddField(
            model_name='goods',
            name='remain',
            field=models.IntegerField(default=0, verbose_name='库存量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Shop', verbose_name='供应商名称'),
        ),
        migrations.AddField(
            model_name='goodsshop',
            name='goods_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Goods'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsshop',
            name='in_price',
            field=models.FloatField(default=0, verbose_name='新进价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(max_length=15, unique=True, verbose_name='商品名称'),
        ),
    ]
