# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20170214_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsaddrecord',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_goods', to='store.Goods', verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goodsaddrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_shop', to='store.Shop', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='recordhistory',
            name='date',
            field=models.DateTimeField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='returnrecord',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_goods', to='store.Goods', verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='returnrecord',
            name='reset_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='重置价格'),
        ),
        migrations.AlterField(
            model_name='returnrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_shop', to='store.Shop', verbose_name='供货商名称'),
        ),
    ]
