# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20161017_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tag',
            field=models.BooleanField(default=True, verbose_name='默认模板'),
        ),
    ]
