# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_report_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssellrecord',
            name='shop',
        ),
        migrations.AlterField(
            model_name='goodssellrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='store.Customer', verbose_name='客户姓名'),
        ),
    ]
