# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20161019_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['last_time', 'goods_name', 'update_date'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_user_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='供应商姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='联系电话'),
        ),
    ]
