# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20161020_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_user_name',
        ),
    ]
