# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20161021_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='average_price',
            field=models.FloatField(default=0, verbose_name='进价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='last_price',
            field=models.FloatField(default=0, verbose_name='售价'),
        ),
    ]
