# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='供货商名称'),
        ),
    ]
