# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0018_auto_20161121_1142'),
    ]
    operations = [
        migrations.CreateModel(
            name='ArrearsPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrears_price', models.FloatField(verbose_name='欠款额')),
                ('is_arrears', models.BooleanField(default=False, verbose_name='清除欠款')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer', verbose_name='客户姓名')),
            ],
            options={
                'verbose_name': '欠款记录',
                'ordering': ['-date'],
                'verbose_name_plural': '欠款记录',
            },
        ),
        migrations.AlterModelOptions(
            name='goodssellrecord',
            options={'ordering': ['-date', 'goods', 'sell_num'], 'verbose_name': '销售记录', 'verbose_name_plural': '销售记录'},
        ),
        migrations.RemoveField(
            model_name='goodssellrecord',
            name='arrears_price',
        ),
        migrations.RemoveField(
            model_name='goodssellrecord',
            name='is_arrears',
        ),
        migrations.AddField(
            model_name='goodssellrecord',
            name='arrears',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrears', to='store.ArrearsPrice', verbose_name='欠款额'),
        ),
    ]
