# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_shop_shop_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系地址')),
                ('phone_number', models.CharField(max_length=20, verbose_name='联系电话')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('user_name', models.CharField(max_length=15, verbose_name='供货商姓名')),
                ('shop_name', models.CharField(max_length=20, verbose_name='供货商名称')),
                ('shop_address', models.CharField(max_length=100, verbose_name='供货商地址')),
            ],
            options={
                'verbose_name': '供货商',
                'verbose_name_plural': '供货商',
                'ordering': ['shop_name'],
            },
        ),
    ]
