# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_shops'),
    ]

    operations = [
        migrations.RunSQL(
            """DROP TABLE "store_shop";"""),
        migrations.RunSQL("""ALTER TABLE "store_shops" RENAME TO "store_shop";""")
    ]
