# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20161121_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shops',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='customer_ptr',
        ),
        migrations.AddField(
            model_name='shop',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=1, verbose_name='添加日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系地址'),
        ),
        migrations.AddField(
            model_name='shop',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, verbose_name='联系电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='user_name',
            field=models.CharField(default=1, max_length=15, verbose_name='供货商姓名'),
            preserve_default=False,
        ),
    ]
